
spring:
  application:
    name: "client"
  cloud:
    config:
      enabled: true
#  profiles:
#    active: prod
#  config:
#    import :
#      - optional:application_${spring.profiles.active}.yml
server:
  port: 8090

build:
  version: 1.1

logging:
  level:
    root: INFO



